spring:
  application:
    name: GreengramTdd
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/greengram2024_tdd
    username: root
    password: green502
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB


mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /swagger # Swagger page? redirect
    operations-sorter: method #alpha(default): url ?? ??, method: http-method ?? ??
    default-model-expand-depth: 10
    default-models-expand-depth: 10
    display-request-duration: true # try it out ? ?? ? request duration(?? ????) ? ??? ???
  cache:
    disabled: true

file:
  directory: D:\Students\DongHyeon\2024-01\download\greengram_tdd\
---
spring:
  config:
    activate:
      on-profile: tdd
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost:3306/greengram2024_tdd_test
  sql:
    init:
      mode: always
#---
#
#spring:
#  config:
#    activate:
#      on-profile: test
#
#file:
#  directory: D:\Students\DongHyeon\2024-01\download\greengram_ver2



